const ENTRY_SCENE_ALIASES = {
  xiaohongshu: 'xiaohongshu_seed',
  style_variation: 'hot_style_remix'
}

export const ENTRY_SCENE_PRESETS = {
  ecommerce_main: {
    label: '电商主图',
    templateType: 'ecommerce_main',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['simple_commute', 'korean_casual'],
    defaultSceneCodes: ['white_studio', 'light_gray_studio'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['ecommerce_main_image', 'white_background'],
    styleMode: 'auto',
    sceneMode: 'auto',
    bodyMode: 'auto',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  },
  flat_lay: {
    entryScene: 'flat_lay',
    label: '平铺图',
    name: '平铺图',
    templateType: 'flat_lay',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['flat_lay_white_ecommerce'],
    defaultSceneCodes: ['pure_white_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['flat_lay_image'],
    styleMode: 'manual',
    sceneMode: 'manual',
    bodyMode: 'auto',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  },
  xiaohongshu_seed: {
    label: '小红书图',
    templateType: 'xiaohongshu_seed',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['french_soft', 'korean_casual', 'ins_casual'],
    defaultSceneCodes: ['city_street', 'cafe_casual', 'lawn_outdoor'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['seed_cover', 'social_post_image'],
    styleMode: 'auto',
    sceneMode: 'auto',
    bodyMode: 'auto',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  },
  cross_border_white: {
    label: '跨境白底图',
    templateType: 'cross_border_white',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['minimal_studio', 'minimal_cool'],
    defaultSceneCodes: ['pure_white_background', 'transparent_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['cross_border_white_image', 'transparent_png'],
    styleMode: 'auto',
    sceneMode: 'auto',
    bodyMode: 'auto',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  },
  new_arrival: {
    label: '新品上新图',
    templateType: 'new_arrival',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['korean_casual', 'simple_commute', 'french_soft'],
    defaultSceneCodes: ['white_studio', 'city_street', 'home_window'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['main_image', 'detail_image', 'scene_image'],
    batchStrategy: 'multi_style_multi_scene',
    styleMode: 'auto',
    sceneMode: 'auto',
    bodyMode: 'auto',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  },
  batch_model: {
    label: '批量模特图',
    templateType: 'batch_model',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['merchant_saved_template_style'],
    defaultSceneCodes: ['merchant_saved_template_scene'],
    defaultBodyType: 'merchant_saved_template_body',
    defaultOutputTypes: ['batch_model_image'],
    batchStrategy: 'same_model_same_style',
    styleMode: 'template',
    sceneMode: 'template',
    bodyMode: 'template',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  },
  hot_style_remix: {
    label: '爆款改款图',
    templateType: 'hot_style_remix',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['follow_original_scene'],
    defaultBodyType: 'follow_original_body',
    defaultOutputTypes: ['remix_design_image'],
    costActionType: 'hot_style_remix',
    styleMode: 'follow_original',
    sceneMode: 'follow_original',
    bodyMode: 'follow_original',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'pattern_adjustment'
  },
  sketch_to_model: {
    entryScene: 'sketch_to_model',
    label: '设计稿成衣图',
    name: '设计稿成衣图',
    templateType: 'sketch_to_model',
    taskType: 'sketch_to_model',
    defaultStyleCodes: ['simple_commute', 'minimal_studio'],
    defaultSceneCodes: ['white_studio'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['design_preview_image'],
    costActionType: 'sketch_to_model',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'sketch_to_model',
    sourceDesignType: 'sketch',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'sketch_to_model'
  },
  image_to_sketch: {
    entryScene: 'image_to_sketch',
    label: '图片转结构线稿',
    name: '图片转结构线稿',
    templateType: 'image_to_sketch',
    taskType: 'image_to_sketch',
    defaultStyleCodes: ['structure_line_art'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: '',
    defaultOutputTypes: ['structure_sketch'],
    costActionType: 'image_to_sketch',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'image_to_sketch',
    sourceDesignType: 'garment_photo',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'image_to_sketch'
  },
  sketch_remix: {
    entryScene: 'sketch_remix',
    label: '线稿改款效果图',
    name: '线稿改款效果图',
    templateType: 'sketch_remix',
    taskType: 'sketch_remix',
    defaultStyleCodes: ['follow_sketch_style'],
    defaultSceneCodes: ['white_studio'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['remix_design_image'],
    costActionType: 'hot_style_remix',
    styleMode: 'manual',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'sketch_remix',
    sourceDesignType: 'line_art',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'pattern_adjustment'
  },
  text_to_sketch: {
    entryScene: 'text_to_sketch',
    label: 'AI款式起稿',
    name: 'AI款式起稿',
    templateType: 'text_to_sketch',
    taskType: 'text_to_sketch',
    defaultStyleCodes: ['manual_style_prompt'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: '',
    defaultOutputTypes: ['style_sketch'],
    costActionType: 'sketch_to_model',
    styleMode: 'manual',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'text_to_sketch',
    sourceDesignType: 'text_prompt',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'pattern_adjustment'
  },
  sketch_to_tech_pack: {
    entryScene: 'sketch_to_tech_pack',
    label: '线稿生成简易工艺结构图',
    name: '线稿生成简易工艺结构图',
    templateType: 'sketch_to_tech_pack',
    taskType: 'sketch_to_tech_pack',
    defaultStyleCodes: ['structure_line_art'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: '',
    defaultOutputTypes: ['reference_tech_pack'],
    costActionType: 'image_to_sketch',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'sketch_to_tech_pack',
    sourceDesignType: 'line_art',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'tech_pack',
    note: '仅生成参考工艺结构说明，需设计师/制版师修正后用于生产沟通'
  },
  print_generate: {
    entryScene: 'print_generate',
    label: 'AI印花生成',
    name: 'AI印花生成',
    templateType: 'print_generate',
    taskType: 'print_generate',
    defaultStyleCodes: ['manual_style_prompt'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: '',
    defaultOutputTypes: ['print_pattern'],
    costActionType: 'print_generate',
    styleMode: 'manual',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'print_generate',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'print_design'
  },
  print_placement: {
    entryScene: 'print_placement',
    label: '一键衣身贴图',
    name: '一键衣身贴图',
    templateType: 'print_placement',
    taskType: 'print_placement',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['print_preview_image'],
    costActionType: 'print_placement',
    styleMode: 'manual',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'print_placement',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'print_design'
  },
  fabric_replace: {
    entryScene: 'fabric_replace',
    label: 'AI面料替换',
    name: 'AI面料替换',
    templateType: 'fabric_replace',
    taskType: 'fabric_replace',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['fabric_preview_image'],
    costActionType: 'fabric_replace',
    styleMode: 'manual',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'fabric_replace',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'fabric_texture'
  },
  color_batch: {
    entryScene: 'color_batch',
    label: '同款多色批量生成',
    name: '同款多色批量生成',
    templateType: 'color_batch',
    taskType: 'color_batch',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['color_batch_images'],
    costActionType: 'basic_recolor',
    styleMode: 'manual',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'color_batch',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'color_batch'
  },
  detail_page_from_photo: {
    entryScene: 'detail_page_from_photo',
    label: '实拍图智能生成详情页',
    name: '实拍图智能生成详情页',
    templateType: 'detail_page_from_photo',
    taskType: 'detail_page_from_photo',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['detail_page_assets'],
    costActionType: 'detail_long_image',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'detail_page_from_photo',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'detail_page'
  },
  detail_closeup: {
    entryScene: 'detail_closeup',
    label: '局部放大细节图',
    name: '局部放大细节图',
    templateType: 'detail_closeup',
    taskType: 'detail_closeup',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['detail_closeup_image'],
    costActionType: 'detail_closeup',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'detail_closeup',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'closeup_detail'
  },
  detail_long_image: {
    entryScene: 'detail_long_image',
    label: '自动排版详情长图',
    name: '自动排版详情长图',
    templateType: 'detail_page_long_image',
    taskType: 'detail_page_long_image',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['detail_page_long_image'],
    costActionType: 'detail_page_template_render',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'detail_page_long_image',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'long_image_layout'
  },
  runway_video: {
    entryScene: 'runway_video',
    label: '一键生成T台走秀短片',
    name: '一键生成T台走秀短片',
    templateType: 'runway_video',
    taskType: 'runway_video',
    defaultStyleCodes: ['follow_original_style'],
    defaultSceneCodes: ['plain_background'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['runway_video'],
    costActionType: 'runway_video_3s',
    styleMode: 'analysis',
    sceneMode: 'analysis',
    bodyMode: 'analysis',
    developmentMode: 'runway_video',
    sourceDesignType: '',
    advancedPanelDefaultOpen: true,
    defaultOpenPanel: 'runway_video'
  },
  default: {
    label: '通用服装出图',
    templateType: 'default',
    taskType: 'ai_model_image',
    costActionType: 'ai_model_image',
    defaultStyleCodes: ['simple_commute'],
    defaultSceneCodes: ['white_studio'],
    defaultBodyType: 'standard',
    defaultOutputTypes: ['main_image'],
    styleMode: 'auto',
    sceneMode: 'auto',
    bodyMode: 'auto',
    advancedPanelDefaultOpen: false,
    defaultOpenPanel: ''
  }
}

export const MVP_ENTRY_SCENE_SET = new Set([
  'ecommerce_main',
  'flat_lay',
  'xiaohongshu_seed',
  'cross_border_white',
  'new_arrival',
  'batch_model',
  'hot_style_remix',
  'sketch_to_model',
  'image_to_sketch',
  'sketch_remix',
  'text_to_sketch',
  'sketch_to_tech_pack',
  'print_generate',
  'print_placement',
  'fabric_replace',
  'color_batch',
  'detail_page_from_photo',
  'detail_closeup',
  'detail_long_image',
  'runway_video',
  'xiaohongshu',
  'style_variation',
  'white_background',
  'main_image'
])

export const ADVANCED_DEFAULT_OPEN_SCENE_SET = new Set([
  'hot_style_remix',
  'style_variation',
  'sketch_to_model',
  'image_to_sketch',
  'sketch_remix',
  'text_to_sketch',
  'sketch_to_tech_pack',
  'print_generate',
  'print_placement',
  'fabric_replace',
  'color_batch',
  'detail_page_from_photo',
  'detail_closeup',
  'detail_long_image',
  'runway_video'
])

function normalizeEntryScene(entryScene) {
  const scene = String(entryScene || '').trim()
  return ENTRY_SCENE_ALIASES[scene] || scene || 'default'
}

export function getEntryScenePreset(entryScene) {
  const normalizedScene = normalizeEntryScene(entryScene)
  return ENTRY_SCENE_PRESETS[normalizedScene] || ENTRY_SCENE_PRESETS.default
}

export function buildDefaultParamsForEntryScene(entryScene) {
  const preset = getEntryScenePreset(entryScene)

  return {
    entryScene: normalizeEntryScene(entryScene),
    templateType: preset.templateType,
    styleMode: preset.styleMode,
    sceneMode: preset.sceneMode,
    bodyMode: preset.bodyMode,
    detectedStyleCodes: [],
    detectedSceneCodes: [],
    detectedBodyType: '',
    selectedStyleCode: '',
    selectedSceneCode: '',
    selectedBodyType: '',
    finalStyleCode: preset.defaultStyleCodes[0] || '',
    finalSceneCode: preset.defaultSceneCodes[0] || '',
    finalBodyType: preset.defaultBodyType || 'standard',
    outputTypes: preset.defaultOutputTypes || [],
    costActionType: preset.costActionType || '',
    batchStrategy: preset.batchStrategy || '',
    taskType: preset.taskType || preset.templateType || '',
    developmentMode: preset.developmentMode || '',
    sourceDesignType: preset.sourceDesignType || '',
    structureAnalysis: {
      necklineType: '',
      sleeveType: '',
      fitType: '',
      lengthType: '',
      pocketType: '',
      waistlineType: '',
      hemType: ''
    },
    techPack: {
      enabled: false,
      status: 'not_generated',
      fileId: '',
      note: ''
    }
  }
}
