export const MEMBERSHIP_TIERS = Object.freeze({
  FREE_TRIAL: 'free_trial',
  SELF_799: 'self_799',
  PRO_1699: 'pro_1699',
  PRO_PLUS_1999: 'pro_plus_1999',
  ENTERPRISE_5999: 'enterprise_5999',
  ENTERPRISE_7999: 'enterprise_7999',
  ENTERPRISE_YEAR_56800: 'enterprise_year_56800'
})

export const MEMBERSHIP_PLAN_CONFIG = Object.freeze({
  [MEMBERSHIP_TIERS.FREE_TRIAL]: Object.freeze({
    tier: MEMBERSHIP_TIERS.FREE_TRIAL,
    name: '免费试用',
    price: 0,
    displayPromoPrice: 0,
    displayOriginalPrice: '',
    priceUnit: '免费体验',
    aiPoints: 20,
    promoTag: '新用户体验',
    billingCycle: 'trial',
    positioning: '基础出图体验',
    monthlyAiQuota: 20,
    monthlyAiPoints: 20,
    monthlyRefineQuota: 0,
    monthlyRunwayVideoQuota: 1,
    maxRunwayDurationSec: 3,
    isPublicMainPlan: true,
    showAsAddonOrCustom: false,
    canUseAdvancedPanel: false,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: false,
    canExportOriginalProtectionPackage: false,
    canUseDesignerAssist: false,
    canUseBatchTemplate: false,
    canUsePrivateModel: false
  }),
  [MEMBERSHIP_TIERS.SELF_799]: Object.freeze({
    tier: MEMBERSHIP_TIERS.SELF_799,
    name: '自助会员',
    price: 799,
    displayPromoPrice: 799,
    displayOriginalPrice: 999,
    futurePrice: 999,
    priceUnit: '月',
    promoTag: '开业优惠',
    lockPriceText: '连续续费锁定办理价',
    billingCycle: 'monthly',
    positioning: 'AI 自助出图',
    monthlyAiQuota: 600,
    monthlyAiPoints: 600,
    monthlyRefineQuota: 0,
    monthlyRunwayVideoQuota: 3,
    maxRunwayDurationSec: 3,
    isPublicMainPlan: true,
    showAsAddonOrCustom: false,
    canUseAdvancedPanel: false,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: false,
    canExportOriginalProtectionPackage: false,
    canUseDesignerAssist: false,
    canUseBatchTemplate: false,
    canUsePrivateModel: false
  }),
  [MEMBERSHIP_TIERS.PRO_1699]: Object.freeze({
    tier: MEMBERSHIP_TIERS.PRO_1699,
    name: '专业会员',
    price: 1699,
    displayPromoPrice: 1699,
    displayOriginalPrice: 2299,
    originalPrice: 2299,
    futurePrice: 1999,
    priceUnit: '月',
    promoTag: '开业重点推荐',
    lockPriceText: '开业前 90 天办理，连续续费锁定 1699',
    recommended: true,
    billingCycle: 'monthly',
    positioning: 'AI 初稿 + 重点图精修',
    monthlyAiQuota: 1200,
    monthlyAiPoints: 1200,
    monthlyRefineQuota: 50,
    monthlyRunwayVideoQuota: 10,
    maxRunwayDurationSec: 10,
    isPublicMainPlan: true,
    showAsAddonOrCustom: false,
    canUseAdvancedPanel: true,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: true,
    canExportOriginalProtectionPackage: true,
    canUseDesignerAssist: false,
    canUseBatchTemplate: true,
    canUsePrivateModel: false
  }),
  [MEMBERSHIP_TIERS.PRO_PLUS_1999]: Object.freeze({
    tier: MEMBERSHIP_TIERS.PRO_PLUS_1999,
    name: '专业加购包',
    price: 1999,
    displayPromoPrice: 1999,
    displayOriginalPrice: '',
    priceUnit: '顾问定制',
    billingCycle: 'custom',
    positioning: '专业能力加购',
    monthlyAiQuota: 0,
    monthlyAiPoints: 0,
    monthlyRefineQuota: 0,
    monthlyRunwayVideoQuota: 0,
    maxRunwayDurationSec: 0,
    isPublicMainPlan: false,
    showAsAddonOrCustom: true,
    canUseAdvancedPanel: true,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: false,
    canExportOriginalProtectionPackage: false,
    canUseDesignerAssist: false,
    canUseBatchTemplate: true,
    canUsePrivateModel: false
  }),
  [MEMBERSHIP_TIERS.ENTERPRISE_5999]: Object.freeze({
    tier: MEMBERSHIP_TIERS.ENTERPRISE_5999,
    name: '企业尊享',
    price: 5999,
    displayPromoPrice: 5999,
    displayOriginalPrice: 7999,
    originalPrice: 7999,
    futurePrice: 7999,
    priceUnit: '月',
    promoTag: '企业托管',
    lockPriceText: '连续续费锁定办理价',
    billingCycle: 'monthly',
    positioning: '设计师托管 + 原创材料包',
    monthlyAiQuota: 4000,
    monthlyAiPoints: 4000,
    monthlyRefineQuota: 100,
    monthlySampleQuota: 2,
    monthlyRunwayVideoQuota: 30,
    maxRunwayDurationSec: 10,
    isPublicMainPlan: true,
    showAsAddonOrCustom: false,
    canUseAdvancedPanel: true,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: true,
    canExportOriginalProtectionPackage: true,
    canUseDesignerAssist: true,
    canUseBatchTemplate: true,
    canUsePrivateModel: true
  }),
  [MEMBERSHIP_TIERS.ENTERPRISE_7999]: Object.freeze({
    tier: MEMBERSHIP_TIERS.ENTERPRISE_7999,
    name: '企业定制包',
    price: 7999,
    displayPromoPrice: 7999,
    displayOriginalPrice: '',
    priceUnit: '顾问定制',
    billingCycle: 'custom',
    positioning: '企业加购与顾问定制',
    monthlyAiQuota: 0,
    monthlyAiPoints: 0,
    monthlyRefineQuota: 0,
    monthlyRunwayVideoQuota: 0,
    maxRunwayDurationSec: 0,
    isPublicMainPlan: false,
    showAsAddonOrCustom: true,
    canUseAdvancedPanel: true,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: true,
    canExportOriginalProtectionPackage: true,
    canUseDesignerAssist: true,
    canUseBatchTemplate: true,
    canUsePrivateModel: true
  }),
  [MEMBERSHIP_TIERS.ENTERPRISE_YEAR_56800]: Object.freeze({
    tier: MEMBERSHIP_TIERS.ENTERPRISE_YEAR_56800,
    name: '企业年包',
    price: 56800,
    displayPromoPrice: 56800,
    displayOriginalPrice: 72800,
    originalPrice: 72800,
    futurePrice: 72800,
    priceUnit: '年',
    promoTag: '年包锁价',
    lockPriceText: '年包客户优先排期',
    billingCycle: 'yearly',
    positioning: '企业尊享年包 + 优先档期',
    monthlyAiQuota: 4000,
    monthlyAiPoints: 4000,
    monthlyRefineQuota: 100,
    monthlySampleQuota: 2,
    monthlyRunwayVideoQuota: 30,
    maxRunwayDurationSec: 10,
    isPublicMainPlan: true,
    showAsAddonOrCustom: false,
    canUseAdvancedPanel: true,
    canCreateRefineOrder: true,
    canCreateOriginalProtectionPackage: true,
    canExportOriginalProtectionPackage: true,
    canUseDesignerAssist: true,
    canUseBatchTemplate: true,
    canUsePrivateModel: true
  })
})

export function getDefaultMembershipTier() {
  return MEMBERSHIP_TIERS.SELF_799
}

export function getMembershipPlan(tier = getDefaultMembershipTier()) {
  return MEMBERSHIP_PLAN_CONFIG[tier] || MEMBERSHIP_PLAN_CONFIG[getDefaultMembershipTier()]
}

export function getMembershipPermissions(tier = getDefaultMembershipTier()) {
  const plan = getMembershipPlan(tier)
  return {
    tier: plan.tier,
    name: plan.name,
    monthlyAiQuota: plan.monthlyAiQuota || plan.monthlyAiPoints || 0,
    monthlyAiPoints: plan.monthlyAiPoints || plan.monthlyAiQuota || 0,
    monthlyRefineQuota: plan.monthlyRefineQuota || 0,
    monthlySampleQuota: plan.monthlySampleQuota || 0,
    monthlyRunwayVideoQuota: plan.monthlyRunwayVideoQuota || 0,
    maxRunwayDurationSec: plan.maxRunwayDurationSec || 0,
    canUseAdvancedPanel: !!plan.canUseAdvancedPanel,
    canCreateRefineOrder: !!plan.canCreateRefineOrder,
    canCreateOriginalProtectionPackage: !!plan.canCreateOriginalProtectionPackage,
    canExportOriginalProtectionPackage: !!plan.canExportOriginalProtectionPackage,
    canUseDesignerAssist: !!plan.canUseDesignerAssist,
    canUseBatchTemplate: !!plan.canUseBatchTemplate,
    canUsePrivateModel: !!plan.canUsePrivateModel
  }
}

export function canUseFeature(tier = getDefaultMembershipTier(), featureKey = '') {
  const permissions = getMembershipPermissions(tier)
  return !!permissions[featureKey]
}
