<template>
  <view class="page">
    <view v-if="loading" class="state">正在读取生产单...</view><view v-else-if="errorMessage" class="state"><text>{{ errorMessage }}</text><button @click="load">重新加载</button></view>
    <template v-else-if="detail">
      <view class="summary"><view class="row"><text class="title">{{ order.patternTitle || '小单生产' }}</text><text class="pill">{{ statusLabel }}</text></view><text class="meta">{{ order.productionOrderNo }} · {{ order.patternVersionNo }} · {{ order.totalQuantity }} 件</text><text class="meta">工厂：{{ order.factoryName || '待确认' }}　交期：{{ order.latestEstimatedDeliveryAt || order.promisedDeliveryAt || '待确认' }}</text><text class="notice">生产必须经过报价确认、质检和交付验收；系统不会自动付款或自动完成订单。</text></view>

      <view class="card"><view class="head"><text>生产资料</text><text>已确认准入</text></view><view class="info"><view><text>尺码数量</text><text>{{ sizeText }}</text></view><view><text>主面料</text><text>{{ order.materials.mainFabric }}</text></view><view><text>里料/辅料</text><text>{{ [order.materials.lining,order.materials.accessories].filter(Boolean).join('；') || '无' }}</text></view><view><text>工艺要求</text><text>{{ order.craftRequirements }}</text></view></view></view>

      <view v-if="order.status==='draft' && access.canInquiry" class="card action"><view class="head"><text>发起工厂询价</text><text>不会自动下单</text></view><picker mode="date" :value="form.quoteDueAt" @change="form.quoteDueAt=$event.detail.value"><view class="control">{{ form.quoteDueAt || '选择报价截止日期' }} ></view></picker><picker mode="date" :value="form.requestedDeliveryAt" @change="form.requestedDeliveryAt=$event.detail.value"><view class="control">{{ form.requestedDeliveryAt || '选择期望交付日期' }} ></view></picker><button class="primary" :disabled="operating || !form.quoteDueAt || !form.requestedDeliveryAt" @click="sendInquiry">发送询价邀请</button></view>

      <view v-if="order.status==='pending_quote' && access.canQuote" class="card action"><view class="head"><text>提交工厂报价</text><text>真实报价</text></view><input v-model="form.amount" type="digit" placeholder="报价总额（元）" /><input v-model="form.leadTimeDays" type="number" placeholder="生产周期（天）" /><picker mode="date" :value="form.estimatedDeliveryAt" @change="form.estimatedDeliveryAt=$event.detail.value"><view class="control">{{ form.estimatedDeliveryAt || '选择预计交付日期' }} ></view></picker><textarea v-model="form.factoryComment" maxlength="800" placeholder="报价说明、含税运费和产能备注" /><button class="primary" :disabled="operating || !quoteReady" @click="submitQuote">提交报价</button></view>

      <view v-if="order.status==='quoted' && access.canConfirmQuote" class="card action"><view class="head"><text>企业确认报价</text><text>确认后进入备料</text></view><text class="action-note">报价：¥{{ Number(order.amount || currentQuote.amount || 0).toFixed(2) }}，预计交付 {{ order.promisedDeliveryAt || currentQuote.estimatedDeliveryAt }}</text><button class="primary" :disabled="operating" @click="simple(confirmQuote,'报价已确认')">确认报价</button></view>
      <view v-if="order.status==='quote_confirmed' && access.canConfirmQuote" class="card action"><text class="action-note">报价已由企业确认，下一步进入面辅料准备。</text><button class="primary" :disabled="operating" @click="simple(startMaterial,'已进入备料')">开始备料</button></view>
      <view v-if="order.status==='pending_material' && access.canMaterial" class="card action"><text class="action-note">请核对主面料、里料、辅料和颜色后再确认就绪。</text><button class="primary" :disabled="operating" @click="simple(confirmMaterial,'面辅料已就绪')">确认面辅料就绪</button></view>
      <view v-if="order.status==='material_ready' && access.canSchedule" class="card action"><textarea v-model="form.operationNote" maxlength="500" placeholder="填写排产日期、产线或排期说明" /><button class="primary" :disabled="operating || !form.operationNote.trim()" @click="simple(scheduleProduction,'已完成排产')">确认排产</button></view>
      <view v-if="['production_scheduled','rework_required'].includes(order.status) && access.canProduce" class="card action"><text class="action-note">{{ order.status==='rework_required' ? '质检未通过，需按质检意见返工。' : '排产已确认，可由工厂开始生产。' }}</text><button class="primary" :disabled="operating" @click="simple(startProduction,order.status==='rework_required'?'已开始返工':'已开始生产')">{{ order.status==='rework_required' ? '开始返工' : '开始生产' }}</button></view>

      <view v-if="order.status==='producing' && access.canProduce" class="card action"><view class="head"><text>生产进度</text><text>按真实进度填写</text></view><input v-model="form.percent" type="number" placeholder="完成比例 0-100" /><textarea v-model="form.progressContent" maxlength="800" placeholder="裁剪、车缝、后整或包装进度" /><picker mode="date" :value="form.progressDeliveryAt" @change="form.progressDeliveryAt=$event.detail.value"><view class="control">{{ form.progressDeliveryAt || '更新预计交期（可选）' }} ></view></picker><picker :range="riskLabels" :value="form.riskIndex" @change="form.riskIndex=Number($event.detail.value)||0"><view class="control">交期风险：{{ riskLabels[form.riskIndex] }} ></view></picker><button class="secondary" :disabled="operating || !form.progressContent.trim()" @click="saveProgress">记录进度</button><button class="primary" :disabled="operating" @click="simple(submitQuality,'已提交质检')">生产完成，提交质检</button></view>

      <view v-if="order.status==='quality_check' && access.canQuality" class="card action"><view class="head"><text>质检结果</text><text>验收人员操作</text></view><view class="quality-options"><text :class="{active:form.qualityResult==='passed'}" @click="form.qualityResult='passed'">质检通过</text><text :class="{active:form.qualityResult==='failed'}" @click="form.qualityResult='failed'">需要返工</text></view><textarea v-model="form.qualityNote" maxlength="1000" placeholder="填写抽检数量、尺寸、工艺、外观和包装结论" /><button class="upload" :disabled="uploading" @click="chooseImages">{{ uploading ? '上传中...' : `上传质检照片（${attachmentIds.length}）` }}</button><button class="primary" :disabled="operating || !form.qualityResult || !form.qualityNote.trim()" @click="qualityResult">提交质检结果</button></view>

      <view v-if="order.status==='ready_to_deliver' && access.canDeliver" class="card action"><view class="head"><text>提交交付</text><text>数量必须一致</text></view><input v-model="form.deliveryQuantity" type="number" placeholder="交付数量" /><input v-model="form.carrier" maxlength="80" placeholder="物流/交付方式" /><input v-model="form.trackingNo" maxlength="100" placeholder="物流单号（可选）" /><textarea v-model="form.deliveryNote" maxlength="800" placeholder="填写包装、箱数和交付说明" /><button class="upload" :disabled="uploading" @click="chooseImages">{{ uploading ? '上传中...' : `上传交付凭证（${attachmentIds.length}）` }}</button><button class="primary" :disabled="operating || !deliveryReady" @click="deliver">确认交付</button></view>
      <view v-if="order.status==='delivered' && access.canComplete" class="card action"><textarea v-model="form.operationNote" maxlength="500" placeholder="填写收货与最终验收说明" /><button class="primary" :disabled="operating || !form.operationNote.trim()" @click="simple(completeOrder,'生产单已完成')">确认收货并完成</button></view>

      <view v-if="progress.length" class="card"><view class="head"><text>生产进度记录</text><text>{{ progress.length }} 条</text></view><view class="records"><view v-for="item in progress" :key="item.progressId"><text>{{ item.percent }}% · {{ item.content }}</text><text>{{ formatDate(item.createdAt) }}</text></view></view></view>
      <view v-if="qualityChecks.length" class="card"><view class="head"><text>质检记录</text><text>历史不可覆盖</text></view><view class="records"><view v-for="item in qualityChecks" :key="item.qualityCheckId"><text>{{ item.result==='passed'?'质检通过':'需要返工' }} · {{ item.note }}</text><text>{{ formatDate(item.createdAt) }}</text></view></view></view>
      <view v-if="deliveries.length" class="card"><view class="head"><text>交付记录</text><text>真实凭证</text></view><view class="records"><view v-for="item in deliveries" :key="item.deliveryId"><text>交付 {{ item.quantity }} 件 · {{ item.note }}</text><text>{{ formatDate(item.deliveredAt) }}</text></view></view></view>
      <button v-if="access.canCancel" class="cancel" :disabled="operating" @click="cancel">取消生产单</button><view class="safe"></view>
    </template>
  </view>
</template>

<script>
import { cancelSmallBatchOrder, completeSmallBatchOrder, confirmSmallBatchMaterial, confirmSmallBatchQuote, getSmallBatchOrder, recordSmallBatchProgress, recordSmallBatchQuality, scheduleSmallBatchProduction, sendSmallBatchInquiry, startSmallBatchMaterial, startSmallBatchProduction as beginProduction, submitSmallBatchDelivery, submitSmallBatchQuality, submitSmallBatchQuote } from '../../utils/production/smallBatchRepository.js'
import { getSmallBatchStatusLabel } from '../../utils/production/smallBatchState.js'
import { uploadUnifiedFiles } from '../../utils/upload/unifiedUploadService.js'

export default {
  data(){return{productionOrderId:'',loading:true,operating:false,uploading:false,errorMessage:'',detail:null,attachmentIds:[],riskLabels:['无风险','低风险','中风险','高风险'],form:{quoteDueAt:'',requestedDeliveryAt:'',amount:'',leadTimeDays:'',estimatedDeliveryAt:'',factoryComment:'',operationNote:'',percent:'',progressContent:'',progressDeliveryAt:'',riskIndex:0,qualityResult:'',qualityNote:'',deliveryQuantity:'',carrier:'',trackingNo:'',deliveryNote:''}}},
  computed:{order(){const value=(this.detail&&this.detail.order)||{};return{...value,materials:value.materials||{},sizeBreakdown:value.sizeBreakdown||[]}},access(){return(this.detail&&this.detail.access)||{}},quotes(){return(this.detail&&this.detail.quotes)||[]},currentQuote(){return this.quotes.find((item)=>item.quoteId===this.order.currentQuoteId)||{}},progress(){return(this.detail&&this.detail.progress)||[]},qualityChecks(){return(this.detail&&this.detail.qualityChecks)||[]},deliveries(){return(this.detail&&this.detail.deliveries)||[]},statusLabel(){return getSmallBatchStatusLabel(this.order.status)},sizeText(){return(this.order.sizeBreakdown||[]).map((item)=>`${item.size} ${item.quantity}件`).join('、')||'未确认'},quoteReady(){return Number(this.form.amount)>0&&Number(this.form.leadTimeDays)>0&&Boolean(this.form.estimatedDeliveryAt)},deliveryReady(){return Number(this.form.deliveryQuantity)===Number(this.order.totalQuantity)&&Boolean(this.form.deliveryNote.trim())}},
  onLoad(options={}){this.productionOrderId=String(options.productionOrderId||'');this.load()},
  methods:{
    async load(){this.loading=true;this.errorMessage='';const result=await getSmallBatchOrder(this.productionOrderId);this.loading=false;if(!result.ok){this.detail=null;this.errorMessage=result.message||'生产单暂时无法读取。';return}this.detail=result.data;this.form.deliveryQuantity=String(this.order.totalQuantity||'');this.attachmentIds=[]},
    async run(action,successText){if(this.operating)return;this.operating=true;const result=await action();this.operating=false;if(!result.ok)return uni.showToast({title:result.message||'操作失败',icon:'none'});uni.showToast({title:successText,icon:'success'});await this.load()},
    simple(action,text){return this.run(()=>action({productionOrderId:this.productionOrderId,note:this.form.operationNote}),text)},
    sendInquiry(){return this.run(()=>sendSmallBatchInquiry({productionOrderId:this.productionOrderId,quoteDueAt:this.form.quoteDueAt,requestedDeliveryAt:this.form.requestedDeliveryAt}),'询价已发送')},
    submitQuote(){return this.run(()=>submitSmallBatchQuote({productionOrderId:this.productionOrderId,amount:this.form.amount,leadTimeDays:this.form.leadTimeDays,estimatedDeliveryAt:this.form.estimatedDeliveryAt,factoryComment:this.form.factoryComment}),'报价已提交')},
    confirmQuote(){return confirmSmallBatchQuote(this.productionOrderId)},startMaterial(){return startSmallBatchMaterial(this.productionOrderId)},confirmMaterial(input){return confirmSmallBatchMaterial(input)},scheduleProduction(input){return scheduleSmallBatchProduction(input)},startProduction(input){return beginProduction(input)},submitQuality(input){return submitSmallBatchQuality(input)},completeOrder(input){return completeSmallBatchOrder(input)},
    saveProgress(){const risks=['none','low','medium','high'];return this.run(()=>recordSmallBatchProgress({productionOrderId:this.productionOrderId,percent:this.form.percent,content:this.form.progressContent,estimatedDeliveryAt:this.form.progressDeliveryAt,risk:risks[this.form.riskIndex]}),'进度已记录')},
    qualityResult(){return this.run(()=>recordSmallBatchQuality({productionOrderId:this.productionOrderId,result:this.form.qualityResult,note:this.form.qualityNote,assetIds:this.attachmentIds}),'质检结果已提交')},
    deliver(){return this.run(()=>submitSmallBatchDelivery({productionOrderId:this.productionOrderId,quantity:this.form.deliveryQuantity,carrier:this.form.carrier,trackingNo:this.form.trackingNo,note:this.form.deliveryNote,assetIds:this.attachmentIds}),'交付记录已提交')},
    chooseImages(){if(this.uploading)return;uni.chooseImage({count:Math.max(1,9-this.attachmentIds.length),sizeType:['compressed'],sourceType:['album','camera'],success:async(result)=>{this.uploading=true;const files=(result.tempFiles||[]).map((file,index)=>({...file,path:file.path||(result.tempFilePaths||[])[index]}));const uploaded=await uploadUnifiedFiles(files,{assetType:'production_image',maxCount:9,targetType:'small_batch_order',targetId:this.productionOrderId,relation:this.order.status});this.uploading=false;if(!uploaded.success)return uni.showToast({title:'生产凭证上传失败，请重试',icon:'none'});this.attachmentIds=[...new Set([...this.attachmentIds,...uploaded.results.map((item)=>item.fileId).filter(Boolean)])].slice(0,9);uni.showToast({title:'照片已上传',icon:'success'})}})},
    cancel(){uni.showModal({title:'取消生产单',editable:true,placeholderText:'请填写取消原因',confirmColor:'#d92d20',success:({confirm,content})=>{if(confirm)this.run(()=>cancelSmallBatchOrder({productionOrderId:this.productionOrderId,reason:content}),'生产单已取消')}})},
    formatDate(value){const date=value?new Date(value):null;return date&&Number.isFinite(date.getTime())?date.toLocaleString():'时间待同步'}
  }
}
</script>

<style scoped>
.page{min-height:100vh;padding:24rpx;background:#f5f6fa;color:#1f2937;box-sizing:border-box}.state,.summary,.card{border:1rpx solid #e4e9f0;border-radius:18rpx;background:#fff}.state{display:flex;align-items:center;flex-direction:column;padding:80rpx 28rpx;color:#667085}.state button{height:70rpx;margin-top:18rpx;border:0;border-radius:12rpx;background:#1677ff;color:#fff;line-height:70rpx}.summary,.card{padding:26rpx}.row,.head{display:flex;align-items:flex-start;justify-content:space-between;gap:16rpx}.title{font-size:32rpx;font-weight:700}.pill{padding:7rpx 12rpx;border-radius:8rpx;background:#fff4e5;color:#9a5700;font-size:20rpx}.meta,.notice{display:block;margin-top:10rpx;color:#667085;font-size:22rpx}.notice{padding:14rpx;border-radius:10rpx;background:#fff8e8;color:#765f39;line-height:1.5}.card{margin-top:18rpx}.head text:first-child{font-size:28rpx;font-weight:700}.head text:last-child{color:#667085;font-size:20rpx}.info{margin-top:14rpx}.info view{display:flex;justify-content:space-between;gap:24rpx;padding:15rpx 0;border-bottom:1rpx solid #edf0f4;font-size:22rpx}.info text:first-child{flex:0 0 120rpx;color:#667085}.info text:last-child{text-align:right}.action input,.control{height:78rpx;margin-top:12rpx;padding:0 18rpx;border-radius:12rpx;background:#f6f8fa;font-size:23rpx;line-height:78rpx;box-sizing:border-box}.action textarea{width:100%;height:145rpx;margin-top:12rpx;padding:18rpx;border-radius:12rpx;background:#f6f8fa;font-size:23rpx;box-sizing:border-box}.action-note{display:block;color:#667085;font-size:22rpx;line-height:1.6}.action button{height:78rpx;margin:14rpx 0 0;border-radius:12rpx;font-size:23rpx;font-weight:700;line-height:78rpx}.action button::after{border:0}.primary{border:0;background:#1677ff;color:#fff}.secondary,.upload{border:1rpx solid #b9d9ff;background:#fff;color:#1677ff}.quality-options{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;margin-top:16rpx}.quality-options text{padding:18rpx;border:1rpx solid #dfe4eb;border-radius:12rpx;text-align:center}.quality-options text.active{border-color:#1677ff;background:#eaf4ff;color:#1677ff;font-weight:700}.records{margin-top:12rpx}.records view{padding:16rpx 0;border-bottom:1rpx solid #edf0f4}.records text{display:block;font-size:22rpx;line-height:1.5}.records text:last-child{margin-top:5rpx;color:#667085;font-size:20rpx}.cancel{height:76rpx;margin-top:18rpx;border:1rpx solid #f0b7b3;border-radius:12rpx;background:#fff;color:#d92d20;font-size:23rpx;line-height:76rpx}.safe{height:calc(40rpx + env(safe-area-inset-bottom))}@media screen and (max-width:350px){.page{padding:18rpx}.info view{flex-direction:column;gap:6rpx}.info text:last-child{text-align:left}}
</style>
