<template>
  <view class="page">
    <view class="hero"><text class="title">创建小单生产单</text><text class="subtitle">仅基于已批准版型和已确认样衣。创建后仍需询价并由企业确认报价。</text><view class="source"><text>{{ sample.patternTitle || '样衣资料' }}</text><text>{{ sample.patternVersionNo || '已批准版本' }} · 样衣已确认</text></view></view>

    <view class="card"><view class="head"><text>尺码与数量</text><text>必填</text></view><view v-for="(item,index) in sizes" :key="item.size" class="size-row"><text>{{ item.size }}</text><input v-model="item.quantity" type="number" maxlength="5" placeholder="数量" /><text>件</text></view><view class="confirm" :class="{ active: confirmations.sizes }" @click="confirmations.sizes = !confirmations.sizes"><text>{{ confirmations.sizes ? '✓' : '' }}</text><text>尺码和数量已确认，共 {{ totalQuantity }} 件</text></view></view>

    <view class="card"><view class="head"><text>面辅料要求</text><text>必填</text></view><input v-model="materials.mainFabric" maxlength="160" placeholder="主面料" /><input v-model="materials.lining" maxlength="160" placeholder="里料（没有可填写无）" /><textarea v-model="materials.accessories" maxlength="500" placeholder="辅料，如拉链、纽扣、松紧带" /><input v-model="materials.color" maxlength="80" placeholder="颜色/色号" /><textarea v-model="materials.requirement" maxlength="800" placeholder="克重、成分、手感、缩水率等要求" /><view class="confirm" :class="{ active: confirmations.materials }" @click="confirmations.materials = !confirmations.materials"><text>{{ confirmations.materials ? '✓' : '' }}</text><text>面辅料要求已确认</text></view></view>

    <view class="card"><view class="head"><text>工艺要求</text><text>必填</text></view><textarea v-model="craftRequirements" maxlength="1500" placeholder="填写车缝、印绣花、整烫、包装及关键质量要求。" /><view class="confirm" :class="{ active: confirmations.craft }" @click="confirmations.craft = !confirmations.craft"><text>{{ confirmations.craft ? '✓' : '' }}</text><text>工艺要求已确认</text></view></view>

    <view class="card"><view class="head"><text>询价工厂</text><text>必须主动选择</text></view><picker v-if="factories.length" :range="factories" range-key="label" :value="factoryIndex" @change="selectFactory"><view class="picker">{{ selectedFactoryLabel || '选择已认证工厂' }} ></view></picker><input v-else v-model="factoryName" maxlength="120" placeholder="填写实际询价工厂名称" /><text class="note">系统不会自动选择工厂，也不会在创建草稿时自动下单。</text></view>

    <view class="bottom"><text>{{ disabledReason || '信息完整，可创建生产草稿' }}</text><button :disabled="Boolean(disabledReason)" @click="createOrder">{{ submitting ? '创建中...' : '创建生产单' }}</button></view><view class="safe"></view>
  </view>
</template>

<script>
import { getSampleOrder, getSampleFactoryOptions } from '../../utils/sample/sampleRepository.js'
import { createSmallBatchDraft } from '../../utils/production/smallBatchRepository.js'

export default {
  data() { return { sampleOrderId: '', sample: {}, factories: [], factoryIndex: 0, factoryId: '', factoryName: '', sizes: ['S','M','L'].map((size) => ({ size, quantity: '' })), materials: { mainFabric: '', lining: '', accessories: '', color: '', requirement: '' }, craftRequirements: '', confirmations: { sizes: false, materials: false, craft: false }, submitting: false, idempotencyKey: '' } },
  computed: {
    totalQuantity() { return this.sizes.reduce((sum, item) => sum + Math.max(0, Number(item.quantity) || 0), 0) },
    selectedFactoryLabel() { const item = this.factories[this.factoryIndex]; return this.factoryId && item ? item.label : '' },
    disabledReason() { if (this.submitting) return '正在创建，请勿重复点击。'; if (!this.sampleOrderId || this.sample.status !== 'confirmed') return '只能基于已确认样衣创建。'; if (!this.confirmations.sizes || !this.totalQuantity) return '请填写并确认尺码数量。'; if (!this.confirmations.materials || !this.materials.mainFabric.trim()) return '请填写并确认面辅料要求。'; if (!this.confirmations.craft || !this.craftRequirements.trim()) return '请填写并确认工艺要求。'; if (!this.factoryId && !this.factoryName.trim()) return '请选择实际询价工厂。'; return '' }
  },
  onLoad(options = {}) { this.sampleOrderId = String(options.sampleOrderId || ''); this.idempotencyKey = `small_batch_${Date.now()}_${Math.random().toString(36).slice(2,8)}`; this.factories = getSampleFactoryOptions().map((item) => ({ ...item, label: `${item.shortName}${item.region ? ` · ${item.region}` : ''}` })); this.loadSample() },
  methods: {
    async loadSample() { const result = await getSampleOrder(this.sampleOrderId); if (!result.ok) return uni.showToast({ title: result.message || '样衣资料无法读取', icon: 'none' }); this.sample = result.data.order || {}; if (this.sample.productionOrderId) return uni.redirectTo({ url: `/package-mobile-enterprise/small-batch-detail/small-batch-detail?productionOrderId=${encodeURIComponent(this.sample.productionOrderId)}` }); const material = this.sample.material || {}; this.materials.mainFabric = material.name || ''; this.materials.color = material.color || ''; this.materials.requirement = [material.composition, material.weight].filter(Boolean).join('，') },
    selectFactory(event) { this.factoryIndex = Number(event.detail.value) || 0; const item = this.factories[this.factoryIndex] || {}; this.factoryId = item.factoryId || ''; this.factoryName = item.name || '' },
    async createOrder() { if (this.disabledReason) return; this.submitting = true; const result = await createSmallBatchDraft({ sampleOrderId: this.sampleOrderId, factoryId: this.factoryId, factoryName: this.factoryName, sizeBreakdown: this.sizes, sizesConfirmed: this.confirmations.sizes, materials: this.materials, materialsConfirmed: this.confirmations.materials, craftRequirements: this.craftRequirements, craftConfirmed: this.confirmations.craft, idempotencyKey: this.idempotencyKey }); this.submitting = false; if (!result.ok) return uni.showToast({ title: result.message || '生产单创建失败', icon: 'none' }); const id = result.data.order.productionOrderId; uni.redirectTo({ url: `/package-mobile-enterprise/small-batch-detail/small-batch-detail?productionOrderId=${encodeURIComponent(id)}`, fail: () => uni.showToast({ title: '生产单已创建，请从生产中心查看', icon: 'none' }) }) }
  }
}
</script>

<style scoped>
.page{min-height:100vh;padding:24rpx;background:#f5f6fa;color:#1f2937;box-sizing:border-box}.hero,.card{padding:26rpx;border:1rpx solid #e4e9f0;border-radius:18rpx;background:#fff}.title,.subtitle{display:block}.title{font-size:36rpx;font-weight:700}.subtitle{margin-top:8rpx;color:#667085;font-size:23rpx;line-height:1.5}.source{display:flex;justify-content:space-between;gap:12rpx;margin-top:20rpx;padding:18rpx;border-radius:12rpx;background:#eef9f2;color:#177245;font-size:22rpx;font-weight:700}.card{margin-top:18rpx}.head{display:flex;justify-content:space-between;gap:12rpx;margin-bottom:14rpx}.head text:first-child{font-size:28rpx;font-weight:700}.head text:last-child{color:#d92d20;font-size:20rpx}.card input,.picker{height:78rpx;margin-top:12rpx;padding:0 18rpx;border-radius:12rpx;background:#f6f8fa;font-size:23rpx;line-height:78rpx;box-sizing:border-box}.card textarea{width:100%;height:150rpx;margin-top:12rpx;padding:18rpx;border-radius:12rpx;background:#f6f8fa;font-size:23rpx;box-sizing:border-box}.size-row{display:grid;grid-template-columns:70rpx 1fr 50rpx;align-items:center;gap:12rpx}.size-row input{margin-top:8rpx}.confirm{display:flex;align-items:center;gap:12rpx;margin-top:18rpx;color:#667085;font-size:22rpx}.confirm text:first-child{display:flex;align-items:center;justify-content:center;width:34rpx;height:34rpx;border:1rpx solid #cdd4df;border-radius:7rpx}.confirm.active{color:#1677ff;font-weight:600}.confirm.active text:first-child{border-color:#1677ff;background:#1677ff;color:#fff}.note{display:block;margin-top:12rpx;color:#667085;font-size:20rpx;line-height:1.5}.bottom{position:fixed;right:0;bottom:0;left:0;z-index:10;padding:14rpx 24rpx calc(14rpx + env(safe-area-inset-bottom));border-top:1rpx solid #e4e9f0;background:rgba(255,255,255,.96)}.bottom text{display:block;margin-bottom:8rpx;color:#667085;font-size:20rpx}.bottom button{height:82rpx;margin:0;border:0;border-radius:12rpx;background:#1677ff;color:#fff;font-size:25rpx;font-weight:700;line-height:82rpx}.bottom button[disabled]{background:#c9d3df}.safe{height:210rpx}@media screen and (max-width:350px){.page{padding:18rpx}.source{flex-direction:column}}
</style>
