<template>
  <view class="page"><view class="hero"><text class="title">小单快反生产</text><text class="subtitle">查看询价、备料、生产、质检和交付进度。</text></view><scroll-view class="filters" scroll-x :show-scrollbar="false"><view class="filter-row"><text v-for="item in filters" :key="item.value" :class="['filter',{active:status===item.value}]" @click="change(item.value)">{{ item.label }}</text></view></scroll-view><view v-if="loading" class="state">加载中...</view><view v-else-if="errorMessage" class="state"><text>{{ errorMessage }}</text><button @click="load">重新加载</button></view><view v-else-if="!items.length" class="state"><text class="state-title">暂无生产单</text><text>已确认样衣可从样衣详情创建小单生产单。</text></view><view v-else class="list"><view v-for="item in items" :key="item.productionOrderId" class="item" @click="open(item)"><view class="row"><text>{{ item.patternTitle || '小单生产' }}</text><text class="pill">{{ label(item.status) }}</text></view><text class="meta">{{ item.patternVersionNo }} · {{ item.totalQuantity }} 件 · {{ item.factoryName || '工厂待确认' }}</text><view class="foot"><text>{{ item.deliveryRisk === 'high' ? '交期高风险' : '按生产状态持续跟进' }}</text><text>查看 ></text></view></view></view><view class="safe"></view></view>
</template>
<script>
import { listSmallBatchOrders } from '../../utils/production/smallBatchRepository.js'
import { getSmallBatchStatusLabel } from '../../utils/production/smallBatchState.js'
export default { data(){return{status:'',loading:false,errorMessage:'',items:[],locked:false,filters:[{value:'',label:'全部'},{value:'pending_quote',label:'待报价'},{value:'producing',label:'生产中'},{value:'quality_check',label:'质检中'},{value:'rework_required',label:'需返工'},{value:'ready_to_deliver',label:'待交付'},{value:'completed',label:'已完成'}]}},onLoad(options={}){if(this.filters.some((item)=>item.value===options.status))this.status=options.status;this.load()},onShow(){if(this._loaded)this.load();this._loaded=true},methods:{async load(){if(this.loading)return;this.loading=true;this.errorMessage='';const result=await listSmallBatchOrders({status:this.status});this.loading=false;if(result.ok)this.items=result.data.items||[];else{this.items=[];this.errorMessage=result.message||'生产单暂时无法读取。'}},change(value){if(value===this.status)return;this.status=value;this.load()},label:getSmallBatchStatusLabel,open(item){if(this.locked)return;this.locked=true;uni.navigateTo({url:`/package-mobile-enterprise/small-batch-detail/small-batch-detail?productionOrderId=${encodeURIComponent(item.productionOrderId)}`,fail:()=>uni.showToast({title:'生产详情暂时无法打开',icon:'none'}),complete:()=>setTimeout(()=>{this.locked=false},600)})}}}
</script>
<style scoped>
.page{min-height:100vh;padding:24rpx;background:#f5f6fa;color:#1f2937;box-sizing:border-box}.hero,.state,.item{border:1rpx solid #e4e9f0;border-radius:18rpx;background:#fff}.hero{padding:28rpx}.title,.subtitle{display:block}.title{font-size:36rpx;font-weight:700}.subtitle{margin-top:8rpx;color:#667085;font-size:23rpx}.filters{margin-top:18rpx;white-space:nowrap}.filter-row{display:inline-flex;gap:12rpx}.filter{padding:14rpx 22rpx;border:1rpx solid #dfe4eb;border-radius:12rpx;background:#fff;color:#667085;font-size:22rpx}.filter.active{border-color:#1677ff;background:#eaf4ff;color:#1677ff;font-weight:700}.state{display:flex;align-items:center;flex-direction:column;margin-top:18rpx;padding:70rpx 28rpx;color:#667085;text-align:center}.state-title{color:#1f2937;font-size:28rpx;font-weight:700}.state button{height:70rpx;margin-top:18rpx;border:0;border-radius:12rpx;background:#1677ff;color:#fff;line-height:70rpx}.list{display:flex;flex-direction:column;gap:16rpx;margin-top:18rpx}.item{padding:24rpx}.row,.foot{display:flex;align-items:center;justify-content:space-between;gap:16rpx}.row>text:first-child{font-size:27rpx;font-weight:700}.pill{padding:7rpx 12rpx;border-radius:8rpx;background:#fff4e5;color:#9a5700;font-size:20rpx}.meta{display:block;margin-top:10rpx;color:#667085;font-size:22rpx}.foot{margin-top:18rpx;padding-top:16rpx;border-top:1rpx solid #edf0f4;color:#1677ff;font-size:21rpx}.safe{height:calc(36rpx + env(safe-area-inset-bottom))}
</style>
